"""empty message

Revision ID: 0f1fc9b91ebb
Revises: 39d1a6bbdc4d
Create Date: 2018-03-29 09:53:29.448495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f1fc9b91ebb'
down_revision = '39d1a6bbdc4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('category', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'category')
    # ### end Alembic commands ###
