"""empty message

Revision ID: 39d1a6bbdc4d
Revises: 
Create Date: 2018-03-29 09:49:29.379843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d1a6bbdc4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('category', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
